stages:
  - package

debian-pack:
  stage: package
  tags:
    - deployer
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    SERVER_HOST: localhost
    SERVER_PORT: 6969
  script:
    - make release-debian
  when: always

image-pack:
  stage: package
  tags:
    - image-deployer
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_USER: admin
    DOCKER_PASSWORD: admin
  script:
    - make release-docker-image
  when: always
